### ISSUE TITLE
Установка в Termux

### ISSUE THREAD

**Issue by Insomnia731** [shamhi/HamsterKombatBot#2410]
Сначала при установке было _error: can't find Rust compiler_, поставил раст, там где была проблема, а именно вот на этом этапе:
_Using cached pydantic_core-2.20.1.tar.gz (388 kB)
Installing build dependencies_
И здесь появлялась эта самая ошибка, теперь на этом месте просто бесконечное ожидание. Подскажите как фиксить.

**Comment by mir-ashiq** [comment]
@Insomnia731 instead of using bot in your phone use a free python hosting

**Comment by Insomnia731** [comment]
> @Insomnia731 instead of using bot in your phone use a free python hosting

Can you recommend me one? Pythonanywhere doesn't connect to the hamster site, and they generally have a white list of the Internet sites.

**Comment by semeer37** [comment]
You can host it in Koyeb.com refer #2249

**Comment by semeer37** [comment]
> @Insomnia731 you can use GitHub Actions to keep it running or use huggingface spaces

Can you elaborate on how to host it using Github Actions(is it free?).

**Comment by mir-ashiq** [comment]
Yes it's free.
Clone this repo and add main.yml file in .github/workflows folder.
Aslo edit .env and add sessions folder with session file inside it.

main.yml:
```
name: Hamster Kombat Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */6 * * *'  # Runs at the 10th minute of every 6-hour interval

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc build-essential libssl-dev --no-install-recommends
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright and Chromium
      run: |
        python -m playwright install --with-deps chromium
        sudo rm -rf /var/lib/apt/lists/*

    - name: Run Hamster Kombat Bot
      run: python main.py -a 2
```
